# see https://docs.searxng.org/admin/engines/settings.html#use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "ultrasecretkey"  # change this!
  limiter: true  # can be disabled for a private instance
  image_proxy: true
  method: "GET"
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
brand:
  issue_url: false
  docs_url: false
  public_instances: false
  wiki_url: false
general:
  debug: false
  instance_name:  "Mid Search"
  privacypolicy_url: false
  donation_url: false
  contact_url: false
  enable_metrics: true
search:
  autocomplete: "duckduckgo"
